<a href="https://colab.research.google.com/github/Premangshu2906/Numpy/blob/main/Numpy_me1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LEARNING NUMPY FROM BASIC

In [ ]:
import numpy as np
np.array([1,2])

array([1, 2])

In [ ]:
import numpy as np
a=np.array([1,2])
print(a)

[1 2]


In [ ]:
#2d array/matrice
b=np.array([[1,2,2],[5,6,7]])
print(b)

[[1 2 2]
 [5 6 7]]


In [ ]:
#3d array or tensor
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
 np.array([1,2],dtype=bool)

array([ True,  True])

In [ ]:
#range (1,5)-- means 1 include hbe 4 taak jabe..
#range(1,10,2)--1,3,5 erom interval e asbe
np.arange(1,5,3)

array([1, 4])

In [ ]:
#reshape (matrice e bhenge debe 2 row 10 col..and the prd of the reshape==array size)
np.arange(1,21).reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#np.ones --value initialization er jnne
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.zeroes
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.34694388, 0.39864587, 0.88317041, 0.63179341],
       [0.17655386, 0.98553388, 0.14524953, 0.84967555],
       [0.5524939 , 0.86314045, 0.01698709, 0.11307504]])

In [ ]:
#linear space (lower limit,upper limit,kota no chai)
np.linspace(-5,5,8,dtype=int)

array([-5, -4, -3, -1,  0,  2,  3,  5])

In [ ]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

ARRAY ATTRIBUTES


In [ ]:
a=np.array(10)
a2=np.arange(8).reshape(2,2,2)

In [ ]:
#ndim tell dimension of the array
a2.ndim

3

In [ ]:
# shape (kota 2d array,row,col)
print(a2.shape)
a2


(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#size
a2.size

8

In [ ]:
#itemsize---memeory te koto size equip korche
a.itemsize


8

CHANGING DATATYPES
**bold text**

In [ ]:
#astype---used to reduce datasize...like int normally
# nei 64...so eta korle 32 hoe jabe
##a2.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**ARRAY** **OPERATION**

In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scaler--operations mathematics er sob kota te apply hbe
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
#relation
a1>3

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operatiosn as duto array r modhe hoche
a1+a2 #if same order er matrice thake then add/sub eisob krte parbo

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

ARRAY FUNCTION


In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1


array([[13., 87., 34.],
       [73.,  4., 66.],
       [29., 93., 20.]])

In [ ]:
#max/min/sum/prd
np.min(a1)
np.max(a1,axis=0) # axis 1 hoche for row


array([73., 93., 66.])

In [ ]:
#mean/median/std/var
np.mean(a1,axis=1)

array([44.66666667, 47.66666667, 47.33333333])

In [ ]:
#dot product(pehle ka col and dusre ka row should match)
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
 np.log(a1)


array([[2.56494936, 4.46590812, 3.52636052],
       [4.29045944, 1.38629436, 4.18965474],
       [3.36729583, 4.53259949, 2.99573227]])

In [ ]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
#round/floor/ceil
np.ceil(a2)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

INDEXING AND SLICING


In [ ]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[0]


np.int64(0)

In [ ]:
a1[6]

np.int64(6)

In [ ]:
a1[-2]

np.int64(8)

In [ ]:
a2=np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,3]

np.int64(7)

In [ ]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,1,0] #locating [kon layer,kon row,kon col]

np.int64(6)

In [ ]:
a3[0,0,0]

np.int64(0)

SLICING


In [ ]:
a1[2:5:1] #5 take omit kore dieche and 1 er gap e dieche

array([2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]# 2nd col

array([ 2,  6, 10])

In [ ]:
a2[2,:]

array([ 8,  9, 10, 11])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[0:3,2:3]

array([[ 2],
       [ 6],
       [10]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

**Iterating**


In [ ]:
for i in a1:
  print(a1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
for i in a3:
  print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
a3


NameError: name 'a3' is not defined

In [ ]:
for i in a2:
  print(i)

NameError: name 'a2' is not defined

In [ ]:
a2=np.arange(13).reshape(3,4)

NameError: name 'np' is not defined

In [ ]:
import numpy as np

a22=np.arange(12).reshape(3,4)


In [ ]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5)) #horizontal stacking

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5)) #vertical stacking

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
 #stack..joining er jonne use hoy
np.hsplit(a4,4) #horizontal split mane vertical e hbe


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.vsplit(a4,3)#req--data differnce krte

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]