<a href="https://colab.research.google.com/github/Premangshu2906/Numpy/blob/main/Numpy_3_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.random.randint(1,100,15)
a

array([29, 72,  9, 76,  8, 80, 61, 29, 19, 91, 98, 96, 55,  9, 97])

In [ ]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[37, 37, 17, 31],
       [39, 57, 87, 39],
       [25, 21, 22, 56],
       [91, 12, 59, 99],
       [34, 87, 45, 74],
       [74, 47, 60, 69]])

In [ ]:
np.sort(b)

array([[17, 31, 37, 37],
       [39, 39, 57, 87],
       [21, 22, 25, 56],
       [12, 59, 91, 99],
       [34, 45, 74, 87],
       [47, 60, 69, 74]])

In [ ]:
np.sort(a)

array([ 8,  9,  9, 19, 29, 29, 55, 61, 72, 76, 80, 91, 96, 97, 98])

In [ ]:
np.sort(b,axis=0)#sort acc to column

array([[25, 12, 17, 31],
       [34, 21, 22, 39],
       [37, 37, 45, 56],
       [39, 47, 59, 69],
       [74, 57, 60, 74],
       [91, 87, 87, 99]])

In [ ]:
# Append(last e add hoe jabe)
a

array([29, 72,  9, 76,  8, 80, 61, 29, 19, 91, 98, 96, 55,  9, 97])

In [ ]:
np.append(a,200)

array([ 29,  72,   9,  76,   8,  80,  61,  29,  19,  91,  98,  96,  55,
         9,  97, 200])

In [ ]:
b

array([[37, 37, 17, 31],
       [39, 57, 87, 39],
       [25, 21, 22, 56],
       [91, 12, 59, 99],
       [34, 87, 45, 74],
       [74, 47, 60, 69]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)#col e add

array([[37., 37., 17., 31.,  1.],
       [39., 57., 87., 39.,  1.],
       [25., 21., 22., 56.,  1.],
       [91., 12., 59., 99.,  1.],
       [34., 87., 45., 74.,  1.],
       [74., 47., 60., 69.,  1.]])

In [ ]:
#concatenate


In [ ]:
#unique
e=np.array([1,2,3,3,4,5,6,7,7,7])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#expand_dms(expand dimension) 1d-->2d,,2d-->3d
a
a.shape


(15,)

In [ ]:
np.expand_dims(a,axis=1)#.shape

array([[29],
       [72],
       [ 9],
       [76],
       [ 8],
       [80],
       [61],
       [29],
       [19],
       [91],
       [98],
       [96],
       [55],
       [ 9],
       [97]])

In [ ]:
#where (index berobe )
a

array([29, 72,  9, 76,  8, 80, 61, 29, 19, 91, 98, 96, 55,  9, 97])

In [ ]:
np.where(a>50)

(array([ 1,  3,  5,  6,  9, 10, 11, 12, 14]),)

In [ ]:
#np.where(condition,true,false)
np.where(a>50,0,a)# 50 er theke boro 0 die replaced

array([29,  0,  9,  0,  8,  0,  0, 29, 19,  0,  0,  0,  0,  9,  0])

In [ ]:
#argmax(biggest element er index pos dei)
import numpy as np
e=np.array([2,1,2,3,3,4,5,6,7,7,7])

np.argmax(e)

np.int64(8)

In [ ]:
np.argmin(e)

np.int64(1)

In [ ]:
#cumsum(cumulative sum--used when we want to compute cum sum over a axis)
np.cumsum(e)

array([ 2,  3,  5,  8, 11, 15, 20, 26, 33, 40, 47])

In [ ]:
#cumprod
np.cumprod(e)

array([      2,       2,       4,      12,      36,     144,     720,
          4320,   30240,  211680, 1481760])

In [ ]:
#percentile
np.percentile(e,50)

np.float64(4.0)

In [ ]:
#Histogram(freq rrange bole in given no)
a=np.random.randint(0,100,40)
print(a)

np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

[50 37  2 77 65  6 53 76 37  6  9  9 78 66 50 15 51 88 47 51 52 40  5 10
 53  1 89 75 33 26 11 85 88 58 57  0 93 94 43 90]


(array([8, 3, 1, 3, 3, 9, 2, 4, 4, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
# Corrcoef(how 2 quantities arre corelated)
#x er value change hole y kemon change hbe
salary=np.array([2000,4000,6000,7000])
exp=np.array([1,2,3,5])
np.corrcoef(salary,exp)

array([[1.        , 0.94625552],
       [0.94625552, 1.        ]])

In [ ]:
#isin--multiple items search korte use hoy
a=np.random.randint(0,50,20)
print(a)

item=[10,20,30,40,50,60,70,80,90]
np.isin(a,item)



[34 44 34 19 17 45 40 40 30 16 46  7 46 36  3 10  2 23 44 22]


array([False, False, False, False, False, False,  True,  True,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False])

In [ ]:
a[np.isin(a,item)]
#kon gulo pelam bolbe


array([40, 40, 30, 10])

In [ ]:
#flip
a
np.flip(a)#first and last no flipped

array([22, 44, 23,  2, 10,  3, 36, 46,  7, 46, 16, 30, 40, 40, 45, 17, 19,
       34, 44, 34])

In [ ]:
b=np.arange(12).reshape(4,3)
print(b)
np.flip(b)#ekbar row wise hbe ekbar column wise

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [ ]:
#put--replaces specific values of an array
print(a)
np.put(a,[19,40],[100,120])

[ 34  44  34  19  17  45  40  40  30  16  46   7  46  36   3  10   2  23
  44 100]


IndexError: index 40 is out of bounds for axis 0 with size 20

In [ ]:
#delete
print(a)
np.delete(a,[3,5])#in answer 19 & 45 is deleted

[ 34  44  34  19  17  45  40  40  30  16  46   7  46  36   3  10   2  23
  44 100]


array([ 34,  44,  34,  17,  40,  40,  30,  16,  46,   7,  46,  36,   3,
        10,   2,  23,  44, 100])

In [ ]:
#set functions
a=np.array([1,2,3,4,5])
b=np.array([1,2,2,4,6])
np.union1d(a,b)


array([1, 2, 3, 4, 5, 6])

In [ ]:
np.setdiff1d(a,b)

array([3, 5])

In [ ]:
np.intersect1d(a,b)

array([1, 2, 4])

In [ ]:
np.setxor1d(a,b)

array([3, 5, 6])

In [ ]:
np.in1d(a,1) #oi item ta present ache naki

/tmp/ipython-input-1506200059.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,1)


array([ True, False, False, False, False])

In [ ]:
#clip--ekta range e value rakhe
a=np.arange(1,100)
print(a)
np.clip(a,a_min=10,a_max=20)# 10 er niche val replace hoe jabe 10 die and 11-20 same thakbe and greater than 20 sob 20 diei

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])